# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: siokim <siokim@student.42seoul.kr>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/11/09 04:40:59 by siokim            #+#    #+#              #
#    Updated: 2022/01/06 15:38:40 by sion             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = gcc
AR = ar
CFLAGS = -Wall -Wextra -Werror
ARFLAGS = -rc
NAME = libft.a

SRCS = ft_bzero.c ft_isalnum.c ft_isalpha.c \
		ft_isascii.c ft_isdigit.c ft_isprint.c \
		 ft_memset.c ft_strchr.c ft_calloc.c\
		ft_strjoin.c ft_strlen.c ft_strrchr.c \
		ft_substr.c ft_tolower.c ft_toupper.c \
		ft_strncmp.c ft_strchr.c ft_atoi.c \
		ft_memcpy.c ft_memmove.c ft_memcmp.c \
		ft_memchr.c ft_strdup.c ft_strlcat.c \
		ft_strlcpy.c ft_strnstr.c ft_itoa.c \
		ft_strmapi.c ft_strtrim.c ft_putchar_fd.c \
		ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c \
		ft_striteri.c ft_split.c

B_SRCS = ft_lstnew.c ft_lstadd_front.c ft_lstsize.c \
			ft_lstlast.c ft_lstadd_back.c ft_lstdelone.c \
			ft_lstclear.c ft_lstiter.c ft_lstmap.c

OBJS = $(SRCS:.c=.o)
B_OBJS = $(B_SRCS:.c=.o)

ifdef WITH_BONUS
	OBJ = $(OBJS) $(B_OBJS)
else
	OBJ = $(OBJS)
endif

.PHONY:all clean fclean re bonus

all: $(NAME)

$(NAME) : $(OBJ)
	$(AR) $(ARFLAGS) $(NAME) $(OBJS)

clean:
	rm -f $(OBJS) $(B_OBJS)

fclean: clean
	rm -f $(NAME)

bonus: 
	@make WITH_BONUS=1 all


re: fclean all
